info:
  name: Producto - Margen calculado
  type: http
  seq: 1

http:
  method: GET
  url: "{{urlVersion1}}/api/connekta/v3/ejecutarconsulta?idCompania={{idCompania}}&descripcion=muellesyfrenos_Margen_Calculado_ERP&parametros=Referencia='-1'|IdItem='116'|Bodega=''1'|Descripcion='-1'|ListaPrecio='-1'"
  headers:
    - name: ConniKey
      value: "{{erpConniKeyConnektaVersion2}}"
    - name: ConniToken
      value: "{{erpConniTokenConnektaVersion2}}"
  params:
    - name: idCompania
      value: "{{idCompania}}"
      type: query
    - name: descripcion
      value: muellesyfrenos_Margen_Calculado_ERP
      type: query
    - name: parametros
      value: Referencia='-1'|IdItem='116'|Bodega=''1'|Descripcion='-1'|ListaPrecio='-1'
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
